import { Document } from "@/app/types/document"

export const loremIpsum = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras venenatis et metus in aliquet. Sed mauris purus, semper ac imperdiet eu, blandit ut eros. Etiam fringilla urna sit amet pellentesque laoreet. Donec pretium ante libero. Maecenas odio mauris, ultrices vel sodales vitae, facilisis quis orci. Proin eget volutpat nulla, quis tristique diam. Vivamus sollicitudin ornare nibh ac volutpat. Sed nec eros molestie, porta mauris ut, laoreet elit. Duis vel augue quis libero pharetra feugiat. Morbi imperdiet iaculis magna, vel faucibus quam maximus vitae. Phasellus vel turpis in eros ultricies dictum in quis odio. Integer porttitor consectetur rhoncus. Nam hendrerit lacus eros, sed ultricies diam hendrerit in.Phasellus vel eros quis dolor dignissim lobortis.Donec eget sapien sit amet arcu semper varius.In hac habitasse platea dictumst.Nunc fermentum ligula non sodales pharetra.Fusce condimentum ex placerat elit dapibus tempor at id tellus.Ut scelerisque facilisis tincidunt.Aliquam vulputate viverra ante, et pretium orci aliquam at.Sed congue tellus ut viverra elementum.Ut sodales ac magna quis malesuada.Nunc non mi vel arcu aliquam sollicitudin nec sit amet metus.Nunc elementum interdum quam, ac semper ligula hendrerit quis.Nunc cursus massa at mauris tincidunt, sit amet dignissim tellus lacinia.Proin id hendrerit est. Donec dui erat, tincidunt non vestibulum ut, semper id leo.Quisque egestas malesuada velit eget eleifend.Donec quis metus id tortor commodo venenatis a eget lectus.Sed ultricies auctor justo, id porttitor sapien.Morbi at cursus erat.Morbi convallis tempor libero, a vehicula nisl sagittis non.Nulla facilisi.Maecenas est neque, ultricies ut lectus non, venenatis feugiat dolor.Nunc vestibulum auctor rutrum.Sed ac erat ut nisi porttitor cursus et viverra quam.In tincidunt pellentesque mauris a pretium.Pellentesque euismod neque sed enim ornare condimentum.Aliquam sed sem condimentum, fermentum arcu id, molestie odio.Phasellus ipsum orci, placerat ut mi volutpat, consectetur convallis risus.Cras dapibus ex in arcu consectetur rhoncus.Ut at nulla tincidunt, ullamcorper ante ac, facilisis arcu. Suspendisse commodo condimentum lacinia.Fusce viverra lorem lacus, dignissim rutrum orci ultricies sed.Nam commodo pretium arcu eget faucibus.Aliquam maximus arcu nec lobortis fermentum.Curabitur auctor justo eu varius auctor.Duis at rhoncus erat, quis consectetur ligula.Duis ante justo, blandit ac dolor faucibus, consequat lobortis magna.Vestibulum tincidunt eleifend purus a consequat.Ut nec nulla pharetra, euismod nibh non, efficitur nulla.Sed mattis ligula venenatis arcu egestas, ut egestas ligula ultricies.Integer quis turpis in sapien posuere rhoncus.Pellentesque pellentesque, sem ut finibus tincidunt, erat dolor bibendum lacus, ac feugiat sem tellus ut diam. Proin pellentesque purus arcu.Proin ac cursus augue.Sed fermentum enim et urna cursus luctus.Proin ac ex viverra, fermentum sapien accumsan, condimentum elit.Sed at porta risus.Cras vel neque aliquam, aliquam turpis id, sollicitudin leo.Duis vitae nisi efficitur augue laoreet sodales quis ac ex.Sed imperdiet auctor augue nec dapibus.Donec luctus porta felis id euismod.Aliquam interdum, dolor eget auctor vehicula, lorem leo semper mauris, ac ornare ex metus ultrices sem.Curabitur bibendum orci commodo erat interdum, eu vulputate mi auctor.Nullam tempor, metus at porttitor faucibus, lorem massa imperdiet quam, in sollicitudin leo est nec ipsum.Duis egestas leo vitae leo dignissim, quis vulputate nibh suscipit.Proin est nisi, elementum a libero eget, commodo ornare magna.Donec libero eros, consectetur vel leo ut, pulvinar fringilla odio."

export const dummyDocuments: Document[] = [
    {
        id: 1,
        page: 1,
        score: 0.98,
        version: "v1",
        text: loremIpsum,
        roll: { id: 1, name: "Roll 001", number_documents: 3 },
    },
    {
        id: 2,
        page: 2,
        score: 0.94,
        version: "v1",
        text: loremIpsum,
        roll: { id: 1, name: "Roll 001", number_documents: 3 },
    },
    {
        id: 3,
        page: 3,
        score: 0.91,
        version: "v1",
        text: loremIpsum,
        roll: { id: 1, name: "Roll 001", number_documents: 3 },
    },
    {
        id: 4,
        page: 1,
        score: 0.87,
        version: "v2",
        text: loremIpsum,
        roll: { id: 2, name: "Roll 002", number_documents: 3 },
    },
    {
        id: 5,
        page: 2,
        score: 0.83,
        version: "v2",
        text: loremIpsum,
        roll: { id: 2, name: "Roll 002", number_documents: 3 },
    },
    {
        id: 6,
        page: 3,
        score: 0.79,
        version: "v2",
        text: loremIpsum,
        roll: { id: 2, name: "Roll 002", number_documents: 3 },
    },
    {
        id: 7,
        page: 1,
        score: 0.95,
        version: "v1",
        text: loremIpsum,
        roll: { id: 3, name: "Roll 003", number_documents: 3 },
    },
    {
        id: 8,
        page: 2,
        score: 0.89,
        version: "v1",
        text: loremIpsum,
        roll: { id: 3, name: "Roll 003", number_documents: 3 },
    },
    {
        id: 9,
        page: 3,
        score: 0.76,
        version: "v2",
        text: loremIpsum,
        roll: { id: 3, name: "Roll 003", number_documents: 3 },
    },
    {
        id: 10,
        page: 1,
        score: 0.93,
        version: "v2",
        text: loremIpsum,
        roll: { id: 4, name: "Roll 004", number_documents: 3 },
    },
    {
        id: 11,
        page: 2,
        score: 0.88,
        version: "v2",
        text: loremIpsum,
        roll: { id: 4, name: "Roll 004", number_documents: 3 },
    },
    {
        id: 12,
        page: 3,
        score: 0.81,
        version: "v3",
        text: loremIpsum,
        roll: { id: 4, name: "Roll 004", number_documents: 3 },
    },
    {
        id: 13,
        page: 1,
        score: 0.97,
        version: "v1",
        text: loremIpsum,
        roll: { id: 5, name: "Roll 005", number_documents: 3 },
    },
    {
        id: 14,
        page: 2,
        score: 0.92,
        version: "v1",
        text: loremIpsum,
        roll: { id: 5, name: "Roll 005", number_documents: 3 },
    },
    {
        id: 15,
        page: 3,
        score: 0.85,
        version: "v2",
        text: loremIpsum,
        roll: { id: 5, name: "Roll 005", number_documents: 3 },
    },
    {
        id: 16,
        page: 1,
        score: 0.90,
        version: "v2",
        text: loremIpsum,
        roll: { id: 6, name: "Roll 006", number_documents: 3 },
    },
    {
        id: 17,
        page: 2,
        score: 0.84,
        version: "v2",
        text: loremIpsum,
        roll: { id: 6, name: "Roll 006", number_documents: 3 },
    },
    {
        id: 18,
        page: 3,
        score: 0.78,
        version: "v3",
        text: loremIpsum,
        roll: { id: 6, name: "Roll 006", number_documents: 3 },
    },
    {
        id: 19,
        page: 1,
        score: 0.96,
        version: "v1",
        text: loremIpsum,
        roll: { id: 7, name: "Roll 007", number_documents: 3 },
    },
    {
        id: 20,
        page: 2,
        score: 0.86,
        version: "v1",
        text: loremIpsum,
        roll: { id: 7, name: "Roll 007", number_documents: 3 },
    },
    {
        id: 21,
        page: 3,
        score: 0.82,
        version: "v2",
        text: loremIpsum,
        roll: { id: 7, name: "Roll 007", number_documents: 3 },
    },
    {
        id: 22,
        page: 1,
        score: 0.99,
        version: "v2",
        text: loremIpsum,
        roll: { id: 8, name: "Roll 008", number_documents: 3 },
    },
    {
        id: 23,
        page: 2,
        score: 0.93,
        version: "v2",
        text: loremIpsum,
        roll: { id: 8, name: "Roll 008", number_documents: 3 },
    },
    {
        id: 24,
        page: 3,
        score: 0.89,
        version: "v3",
        text: loremIpsum,
        roll: { id: 8, name: "Roll 008", number_documents: 3 },
    },
    {
        id: 25,
        page: 1,
        score: 0.91,
        version: "v1",
        text: loremIpsum,
        roll: { id: 9, name: "Roll 009", number_documents: 3 },
    },
    {
        id: 26,
        page: 2,
        score: 0.87,
        version: "v1",
        text: loremIpsum,
        roll: { id: 9, name: "Roll 009", number_documents: 3 },
    },
    {
        id: 27,
        page: 3,
        score: 0.80,
        version: "v2",
        text: loremIpsum,
        roll: { id: 9, name: "Roll 009", number_documents: 3 },
    },
    {
        id: 28,
        page: 1,
        score: 0.95,
        version: "v2",
        text: loremIpsum,
        roll: { id: 10, name: "Roll 010", number_documents: 3 },
    },
    {
        id: 29,
        page: 2,
        score: 0.88,
        version: "v3",
        text: loremIpsum,
        roll: { id: 10, name: "Roll 010", number_documents: 3 },
    },
    {
        id: 30,
        page: 3,
        score: 0.83,
        version: "v3",
        text: loremIpsum,
        roll: { id: 10, name: "Roll 010", number_documents: 3 },
    },
];